export enum ComponentBuilderRoute {
 Start = 'components/start',
 OpenBuilder = 'components/open',
 LoadPick = 'components/loadPick',
 LoadOpen = 'components/loadOpen',
 DeleteSaved = 'components/deleteSaved',

 Node = 'components/node',
 Action = 'components/action',
 AddAt = 'components/addAt',
 AddPick = 'components/addPick',
 BindSystem = 'components/bindSystem',
 BindAction = 'components/bindAction',
 BindChoice = 'components/bindChoice',
 ShowDesign = 'components/showDesign',
 SwitchDesign = 'components/switchDesign',
 EditorSave = 'components/editorSave',
 OptionsSave = 'components/optionsSave',
 MediaAddSave = 'components/mediaAdd',
 Empty = 'components/empty',

 ImportJson = 'components/import',
 ImportSave = 'components/importSave',
 ExportJson = 'components/export',
 Placeholders = 'components/placeholders',

 Save = 'components/save',
 SaveSubmit = 'components/saveSubmit',

 Send = 'components/send',
 SendTo = 'components/sendTo',
 WebhookModal = 'components/webhook',
 WebhookSubmit = 'components/webhookSubmit',
 WebhookSendTo = 'components/webhookSendTo',
 EditMessage = 'components/editMsg',
 EditMessageSubmit = 'components/editMsgSave',
 Back = 'components/back',

 CloseThread = 'components/close',
}
