export const tagCommandName = 'tag';

export enum TicketRoute {
 Create = 'tickets/create',
 Claim = 'tickets/claim',
 Unclaim = 'tickets/unclaim',
 Take = 'tickets/take',
 UserInfo = 'info/user',
 Escalate = 'tickets/escalate',
 EscalateTo = 'tickets/escalateTo',
 Close = 'tickets/close',
 CloseReason = 'tickets/closeReason',
 Leave = 'tickets/leave',
 Delete = 'tickets/delete',
 KeepOpen = 'tickets/keepopen',

 TagSend = 'tickets/tagSend',
 TagPage = 'tickets/tagPage',
 TagSearch = 'tickets/tagSearch',
 TagSearchModal = 'tickets/tagSearchModal',
 TagAdd = 'tickets/tagAdd',
 TagAddModal = 'tickets/tagAddModal',
 TagEdit = 'tickets/tagEdit',
 TagEditModal = 'tickets/tagEditModal',
 TagDelete = 'tickets/tagDelete',
 TagManage = 'tickets/tagManage',
 TagBrowse = 'tickets/tagBrowse',

 RoleMap = 'tickets/rolemap',
 RoleMapAdd = 'tickets/rolemap/add',
 RoleMapEdit = 'tickets/rolemap/edit',
 RoleMapRemove = 'tickets/rolemap/remove',
 RoleMapUp = 'tickets/rolemap/up',
 RoleMapDown = 'tickets/rolemap/down',
 RoleMapPage = 'tickets/rolemap/page',
 RoleMapSave = 'tickets/rolemap/save',

 TierManage = 'tickets/tierManage',
 TierAdd = 'tickets/tierAdd',
 TierEdit = 'tickets/tierEdit',
 TierDel = 'tickets/tierDel',
 TierUp = 'tickets/tierUp',
 TierDown = 'tickets/tierDown',
 TierPage = 'tickets/tierPage',
 TierSave = 'tickets/tierSave',

 Panel = 'tickets/panel',
 PanelAdd = 'tickets/panel/add',
 PanelEdit = 'tickets/panel/edit',
 PanelPost = 'tickets/panel/post',
 PanelRemove = 'tickets/panel/remove',
 PanelPage = 'tickets/panel/page',
 PanelSave = 'tickets/panel/save',
 PanelLabel = 'tickets/panel/label',
 PanelLabelSave = 'tickets/panel/labelsave',
 PanelPick = 'tickets/panelPick',

 ClearBotToken = 'tickets/clearBotToken',
 InviteBot = 'tickets/inviteBot',

 IntakeOpen = 'tickets/intakeOpen',
 IntakeExisting = 'tickets/intakeExisting',
 IntakeServer = 'tickets/intakeServer',
 IntakeKind = 'tickets/intakeKind',
}
