[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.64"
regex = "1.9.3"
wasm-bindgen = "0.2.87"

[lib]
crate-type = ["cdylib"]